# Generated by Django 5.1.3 on 2024-12-04 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownlog',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_breakdowns', to='maintenance.machine'),
        ),
        migrations.AlterField(
            model_name='breakdownlog',
            name='mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanic_breakdowns', to='user_management.employee'),
        ),
        migrations.AlterField(
            model_name='breakdownlog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_breakdowns', to='user_management.employee'),
        ),
    ]
